### ISSUE TITLE
alert mail notification - HTML error 

### ISSUE THREAD

**Issue by hans-mayer** [p-alik/nfsen#13]
Dear All,

I am running nfsen the latest version from this git repository. So far almost all is working  fine. I have only an issue with the "Alerts" page. When in the "action" area "no action" is defined than everything is OK. But of course this makes no sense. If I select "Send alert email" and I enter a valid e-mail address, after pressing the "commit changes" button I got this ugly HTML error: 

This page isn’t working 
nfsen.my.domain  is currently unable to handle this request.
HTTP ERROR 500

In etc/nfsen.conf there are these varaiables defined: $MAIL_FROM , $SMTP_SERVER , $MAIL_BODY 

But obviously something is missing or wrong. 

Any idea where I can start to look for a solution of this issue ? 

Kind regards
Hans

**Comment by p-alik** [comment]
> Any idea where I can start to look for a solution of this issue ?

The issue was mentioned in the mailing list:
https://sourceforge.net/p/nfsen/mailman/message/36517464/
There is a patch proposal also.

**Comment by hans-mayer** [comment]
Dear Alexei,

Many thanks for your reply. 
I applied this patch but it doesn't help. "sendmail" is configured well and can send e-mails. I am using perl v5.26.1 and the following modules are installed. 

```
bareword::filehandles
B::Hooks::OP::Check
Capture::Tiny
Class::Method::Modifiers
Class::XSAccessor
Data::OptList
Devel::GlobalDestruction
Devel::StackTrace
Email::Abstract
Email::Address
Email::Date::Format
Email::Sender
Email::Simple
ExtUtils::Depends
indirect
IO
IO::Socket::SSL
Module::Pluggable
Moo
MooX::Types::MooseLike
Mozilla::CA
MRO::Compat
multidimensional
Params::Util
Role::Tiny
strictures
Sub::Exporter
Sub::Exporter::Progressive
Sub::Install
Sub::Name
Sub::Quote
Test::Fatal
Test::Number::Delta
Test::Requires
Throwable
Try::Tiny

```
If I press the "Commit Changes"  button the following lines appear in /var/log/debug

```
Jan 23 17:59:28 hpg911 nfsen[1694]: connection on UNIX socket
Jan 23 17:59:28 hpg911 nfsen[1694]: comm server started: 5095
Jan 23 17:59:28 hpg911 nfsen[5095]: Cmd Decode: get-globals
Jan 23 17:59:28 hpg911 nfsen[5095]: Cmd Decode: get-du
Jan 23 17:59:28 hpg911 nfsen[5095]: comm child[5096] terminated with no exit value
Jan 23 17:59:28 hpg911 nfsen[5095]: Cmd Decode: get-profile
Jan 23 17:59:28 hpg911 nfsen[5095]: Cmd Decode: run-nfdump
Jan 23 17:59:28 hpg911 nfsen[5095]: Failed: Failed to read from socket:  at /var/cache/nfsen/libexec/Nfcomm.pm line 1148, <STDIN> line 15.
Jan 23 17:59:28 hpg911 nfsen[1694]: comm child[5095] terminated Exit: 0, Signal: 13, Core: 0

```

Any ideas ? 


// Hans

**Comment by p-alik** [comment]
I beg your pardon for delay, Hans.

> Jan 23 17:59:28 hpg911 nfsen[5095]: Failed: Failed to read from socket:  at /var/cache/nfsen/libexec/Nfcomm.pm line 1148, <STDIN> line 15.

The error message isn't very helpful.

> Any ideas ?

Unfortunately I can't reproduce the error in my environment. I used following `t/05-nf-alert.t` script for the purpose.

```perl 
use strict;
use warnings;
use Test::More;

use_ok "NfAlert";
use_ok "NfConf";

my $cf = "etc/nfsen.conf";

ok NfConf::LoadConfig($cf), "LoadConfig($cf)";

subtest "ExecuteAction",  sub {
  my $alert = "no idea";
  my $alertref = {
    action_type => 1, 
    action_email => 'apastuchov@ip-platform.net', 
    action_subject => "a subject", 
  };

  my $timeslot = 1;

  is NfAlert::ExecuteAction($alert, $alertref, undef, $timeslot), '', "NfAlert::ExecuteAction";
};

done_testing();
```

Could you try execute following script in order to get the proper exception, please?

```
$ prove -vI libexec/ t/05-nf-alert.t
t/05-nf-alert.t ..
ok 1 - use NfAlert;
ok 2 - use NfConf;
ok 3 - LoadConfig(etc/nfsen.conf)
    # Subtest: ExecuteAction
    ok 1 - NfAlert::ExecuteAction
    1..1
ok 4 - ExecuteAction
1..4
ok
All tests successful.
Files=1, Tests=4,  0 wallclock secs ( 0.00 usr  0.05 sys +  0.00 cusr  0.17 csys =  0.22 CPU)
Result: PASS
```

**Comment by hans-mayer** [comment]
Dear Alexei,

Many thanks coming back.  
I tried your test, but I think I run into a different issue in the first attempt. It doesn't find "etc/nfsen.conf" but it's there. 

<pre> 
www-data@hpg911:/var/cache/nfsen$ prove -vI libexec/ t/05-nf-alert.t
t/05-nf-alert.t ..
ok 1 - use NfAlert;
ok 2 - use NfConf;
not ok 3 - LoadConfig(etc/nfsen.conf)
# Subtest: ExecuteAction
do "etc/nfsen.conf" failed, '.' is no longer in @INC; did you mean do "./etc/nfsen.conf"? at /var/cache/nfsen/libexec/NfConf.pm line 169.

#   Failed test 'LoadConfig(etc/nfsen.conf)'
#   at t/05-nf-alert.t line 10.
    ok 1 - NfAlert::ExecuteAction
    1..1
ok 4 - ExecuteAction
1..4
# Looks like you failed 1 test of 4.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests

Test Summary Report
-------------------
t/05-nf-alert.t (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=1, Tests=4,  0 wallclock secs ( 0.04 usr  0.01 sys +  0.41 cusr  0.04 csys =  0.50 CPU)
Result: FAIL
</pre> 

But the config is there
 <pre>
www-data@hpg911:/var/cache/nfsen$ ls -lad "etc/nfsen.conf"
-rw-r--r-- 1 root www-data 9954 Dec 30 21:44 etc/nfsen.conf
</pre> 

I am not a perl guru. So how to add '.' to INC ? 
So I changed "t/05-nf-alert.t" a little bit

<pre>
  my $cf = "./etc/nfsen.conf";
</pre> 

And now the test script is running fine: 

<pre>
www-data@hpg911:/var/cache/nfsen$ prove -vI libexec/ t/05-nf-alert.t
t/05-nf-alert.t ..
ok 1 - use NfAlert;
ok 2 - use NfConf;
ok 3 - LoadConfig(./etc/nfsen.conf)
# Subtest: ExecuteAction
    ok 1 - NfAlert::ExecuteAction
    1..1
ok 4 - ExecuteAction
1..4
ok
All tests successful.
Files=1, Tests=4,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.33 cusr  0.05 csys =  0.41 CPU)
Result: PASS
</pre> 

I don't think you got an e-mail. I changed the test script and used my e-mail address. I got it now.

So why do I get this ugly HTML error ? 


Kind regards 
Hans 

--

**Comment by p-alik** [comment]
> And now the test script is running fine

Is it running fine with patched or unpatched version of NfAlert.pm?
I run it without patching.
> So why do I get this ugly HTML error ?

I haven't faintest idea yet, but regarding to the test you haven't any issue with sending email. I'll see for the reason.

**Comment by hans-mayer** [comment]
> Is it running fine with patched or unpatched version of NfAlert.pm?

Originally I was running it without patch. Then I read about the patch and I tried it. But the same error. No difference. 

> .... you haven't any issue with sending email

Actually it doesn't happen when sending an e-mail. It happens when I try to enter an e-mail address. I think at that time it will not try to send an e-mail. If I fill out the form without e-mail notification it works fine. 

// Hans

**Comment by p-alik** [comment]
Hans,

> HTTP ERROR 500

I mislead you to run riot by looking for exception's reason. PHP throws 500.
Is there an exception in Apache log file?
If no, you could configure PHP as described in this post https://stackoverflow.com/a/20511956/2789312

**Comment by hans-mayer** [comment]
Hi, 

Sorry for delay. I was on vacation. 
I made the change in php.ini 
Now I see the following error: 

`[Tue Feb 05 13:58:33.986466 2019] [php7:error] [pid 19603] [client] PHP Fatal error:  Uncaught Error: Call to undefined function ereg() in /var/www/html/nfsen/alerting.php:118\nStack trace:\n#0 /var/www/html/nfsen/nfsen.php(222): check_email_address('..........', Array)\n#1 /var/www/html/nfsen/alerting.php(1326): ParseForm(Array)\n#2 /var/www/html/nfsen/nfsen.php(689): Process_alert_tab(0, 0)\n#3 {main}\n  thrown in /var/www/html/nfsen/alerting.php on line 118, referer: http://nfsen.ict.iiasa.ac.at/nfsen/nfsen.php
`

Of course I entered a correct e-mail. 
But I have a workaround now. I commented out the following lines 

```
                if ( !ereg("^[A-Za-z0-9_\.@-]{6,128}$", $email) ) {
                        SetMessage('error', "Error illegal characters in email address '$email'");
                        return 1;
                }

```

And it works. 
Obviously php7 doesn't understand  ereg() anymore. 

Kind regards
Hans

**Comment by p-alik** [comment]
> Obviously php7 doesn't understand ereg() anymore.

Yes, php7 doesn't contain `ereg` any more. See https://secure.php.net/manual/en/function.ereg.php

Regarding to the [proposal](https://stackoverflow.com/a/35355700/2789312) `ereg` could be replaced by `preg_match`.  I hope https://github.com/p-alik/nfsen/commit/237279b22dae96a42097b8dd41b4471e51090f6f solves the issue.

**Comment by hans-mayer** [comment]
Hi Alexei,
This function is known by php7 now and doesn't generate an HTML error. 
But the regex seems to be wrong. I get 

ERROR: Error illegal characters in email address 'first.family@my.domain.com'!

Kind regards
Hans

**Comment by p-alik** [comment]
Hi Hans,
https://github.com/p-alik/nfsen/commit/f90b4b7ede190accfc1e2de900484072b2a4f613 should solve the issue. It based on native php function [filter_var](https://secure.php.net/manual/en/function.filter-var.php), which is available since php5.

The tests succeeded at http://phptester.net/ with following snippets for three available php versions. 
```php
<?php

$email = "first.family@my.domain.com";
if ( filter_var($email, FILTER_VALIDATE_EMAIL) === false ) {
  print("Error illegal characters in email address '$email'");
} else {
  print("email '$email' is ok");
}
```

**Comment by hans-mayer** [comment]
Yes, it's working. 
Obviously I had some old code in this php script because of a merge issue with git. 

Many thanks.

// Hans
