### ISSUE TITLE
ERROR: nfsend connect()

### ISSUE THREAD

**Issue by NatalNW** [p-alik/nfsen#15]
When I open web page in http://10.0.0.22/nfsen/nfsen.php, I get this errors

> ERROR: nfsend connect() error: No such file or directory!
> ERROR: nfsend - connection failed!!
> ERROR: Can not initialize globals!

How can I fix it?

**Comment by p-alik** [comment]
> How can I fix it?

Try to work through [google](https://www.google.com/search?sxsrf=ACYBGNSe2RktA-0Bhcn5--AfGNmYaqANTw%3A1576050602713&source=hp&ei=qp_wXZOUKITTkwXC5pe4BQ&q=nfsend+connect%28%29+error%3A+No+such+file+or+directory&oq=nfsend+connect%28%29+error%3A+No+such+file+or+directory&gs_l=psy-ab.3..0j0i22i30l3.298.298..656...1.0..0.70.70.1......0....2j1..gws-wiz.5Sl5Xq9-l7w&ved=0ahUKEwiTkceCjq3mAhWE6aQKHULzBVcQ4dUDCAg&uact=5) results.

**Comment by NatalNW** [comment]
I already solved my problem. There was a bug on nfsen version that i was using, then I changed the version.
Thanks!
