### ISSUE TITLE
Keep state of detail

### ISSUE THREAD

**Issue by sebastian-be** [p-alik/nfsen#3]
Hi
I would suggest to keep state of details page between profile changes, as this would allow to make direct comparisons between different views of data, just by switch of the profile. Currently properties such as: type, position, scale, protocol, ... are lost.
For example: with a single "live" profile, but multiple shadow profiles, direct comparison between different views is quite handy.

I've also increased font size in lookup frame, as it was quite small.

Thx

[keepstatstate.patch.txt](https://github.com/p-alik/nfsen/files/2194397/keepstatstate.patch.txt)

**Comment by p-alik** [comment]
[nfsen-1.3.7-dynamic-cycletime](https://github.com/p-alik/nfsen/releases/tag/nfsen-1.3.7-dynamic-cycletime) contains the patch.
Thank you.
